import type {ProjectContext, SourceToolInfo} from '../shared.js';
import path from 'node:path';
import ts from 'typescript';
import {generateTypeSchema} from '../typescript-to-zod.js';

function generateSchema(tool: SourceToolInfo, checker: ts.TypeChecker): string {
  const params = tool.parameters
    .map((param) => {
      const schema = generateTypeSchema(param.type, checker);
      const wrappedSchema = param.optional ? `z.optional(${schema})` : schema;
      return `${param.name}: ${wrappedSchema}`;
    })
    .join(',\n  ');

  return `z.object({
  ${params}
})`;
}

function generateTool(tool: SourceToolInfo, checker: ts.TypeChecker): string {
  const params =
    tool.parameters.length > 0
      ? `{${tool.parameters.map((p) => p.name).join(', ')}`
      : '';
  return `
server.tool(
  {
    name: ${JSON.stringify(tool.name)},
    description: ${tool.description ? JSON.stringify(tool.description) : 'undefined'},
    schema: ${generateSchema(tool, checker)}
  },
  async (${params}) => {
    return ${tool.name}(${tool.parameters.map((p) => p.name).join(', ')});
  },
);
  `.trim();
}

export const template = (context: ProjectContext): string => {
  const relativeSourcePath = path.relative(
    path.dirname(context.outputFilePath),
    context.sourceFilePath
  );
  const normalizedSourcePath = (
    relativeSourcePath.startsWith('.')
      ? relativeSourcePath
      : `./${relativeSourcePath}`
  ).replace(/\\/g, '/');
  const importNames = context.tools.map((t) => t.name).join(', ');
  const imports =
    importNames.length > 0
      ? `import {${importNames}} from ${JSON.stringify(normalizedSourcePath)};`
      : '';
  const tools = context.tools
    .map((t) => generateTool(t, context.typeChecker))
    .join('\n\n');

  return `
// Generated by mcp-compiler - do not edit manually
import {McpServer} from 'tmcp';
import {ZodJsonSchemaAdapter} from '@tmcp/adapter-zod';
import {StdioTransport} from '@tmcp/transport-stdio';
import {z} from 'zod/mini';
${imports}

const adapter = new ZodJsonSchemaAdapter();
const server = new McpServer(
  {
    name: ${JSON.stringify(context.name)},
    version: ${JSON.stringify(context.version)},
    description: ${context.description ? JSON.stringify(context.description) : 'undefined'},
  },
  {
    adapter,
    capabilities: {
    },
  },
);

${tools}

const transport = new StdioTransport(server);
transport.listen();
  `.trim();
};
